---
refresh_interval: 5 # seconds
max_price: 750 # dollars
urls:
  - https://www.amazon.com/PlayStation-5-Console/dp/B08FC5L3RG
  - https://www.bestbuy.com/site/sony-playstation-5-console/6426149.p?skuId=6426149
  - https://www.bestbuy.com/site/sony-playstation-5-digital-edition-console/6430161.p?skuId=6430161
  - https://www.newegg.com/p/N82E16868110291
  - https://www.newegg.com/p/N82E16868110292
  - https://www.newegg.com/p/N82E16868110293
  - https://www.walmart.com/ip/PlayStation-5-Console/363472942
  - https://www.bhphotovideo.com/c/product/1595083-REG/sony_3005718_playstation_5_gaming_console.html
  - https://www.gamestop.com/video-games/playstation-5/consoles/products/playstation-5/11108140.html
  - https://www.gamestop.com/video-games/playstation-5/consoles/products/playstation-5/B225169V.html
  - https://direct.playstation.com/en-us/consoles/console/playstation5-console.3005816
  - https://www.target.com/p/playstation-5-console/-/A-81114595
  - https://www.bestbuy.com/site/combo/ps5-consoles/96be4c49-d98e-47c6-9a68-291c646d0e47
...
