---
refresh_interval: 45 # seconds
urls:
  - https://www.amazon.com/ASUS-Graphics-DisplayPort-Military-Grade-Certification/dp/B08HH5WF97
  - https://www.amazon.com/MSI-GeForce-RTX-3080-10G/dp/B08HR7SV3M
  - https://www.amazon.com/NVIDIA-GeForce-Graphics-DisplayPort-Bearings/dp/B08NQ78BCN
  - https://www.amazon.com/dp/B08HR3Y5GQ/
  - https://www.bestbuy.com/site/nvidia-geforce-rtx-3080-10gb-gddr6x-pci-express-4-0-graphics-card-titanium-and-black/6429440.p?skuId=6429440
  - https://www.bestbuy.com/site/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6-pci-express-4-0-graphics-card/6432400.p?skuId=6432400
  - https://www.bestbuy.com/site/xfx-amd-radeon-rx-6800xt-16gb-gddr6-pci-express-4-0-gaming-graphics-card-black/6441226.p?skuId=6441226 # radeon
  - https://www.newegg.com/asus-geforce-rtx-3080-rog-strix-rtx3080-o10g-gaming/p/N82E16814126457
  - https://www.newegg.com/asus-geforce-rtx-3080-tuf-rtx3080-10g-gaming/p/N82E16814126453
  - https://www.newegg.com/asus-geforce-rtx-3080-tuf-rtx3080-o10g-gaming/p/N82E16814126452
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3881-kr/p/N82E16814487522
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3883-kr/p/N82E16814487521
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3885-kr/p/N82E16814487520
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3895-kr/p/N82E16814487519
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3897-kr/p/N82E16814487518
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080aorus-m-10gd/p/N82E16814932336
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080aorus-x-10gd/p/N82E16814932345
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080eagle-10gd/p/N82E16814932367
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080eagle-oc-10gd/p/N82E16814932330
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080gaming-oc-10gd/p/N82E16814932329
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080vision-oc-10gd/p/N82E16814932337
  - https://www.newegg.com/msi-geforce-rtx-3080-rtx-3080-gaming-x-trio-10g/p/N82E16814137597
  - https://www.newegg.com/msi-geforce-rtx-3080-rtx-3080-ventus-3x-10g-oc/p/N82E16814137598
  - https://www.newegg.com/msi-geforce-rtx-3080-rtx-3080-ventus-3x-10g/p/N82E16814137600
  - https://www.newegg.com/msi-geforce-rtx-3080-rtx3080-suprim-x-10g/p/N82E16814137609
  - https://www.bhphotovideo.com/c/product/1595985-REG/pny_technologies_vcg308010tfxppb_geforce_rtx_3080_10gb.html
  - https://www.bhphotovideo.com/c/product/1592969-REG/zotac_zt_a30800d_10p_gaming_geforce_rtx_3080.html
  - https://www.bhphotovideo.com/c/product/1593332-REG/gigabyte_gv_n3080eagle_oc_10gd_geforce_rtx_3080_eagle.html
  - https://www.bhphotovideo.com/c/product/1593333-REG/gigabyte_gv_n3080gaming_oc_10gd_geforce_rtx_3080_gaming.html
  - https://www.bhphotovideo.com/c/product/1593645-REG/msi_geforce_rtx_3080_gaming.html
  - https://www.bhphotovideo.com/c/product/1593646-REG/msi_geforce_rtx_3080_ventus.html
  - https://www.bhphotovideo.com/c/product/1593649-REG/asus_tuf_rtx3080_10g_gaming_tuf_gaming_geforce_rtx.html
  - https://www.bhphotovideo.com/c/product/1593650-REG/asus_tuf_rtx3080_o10g_gaming_tuf_gaming_geforce_rtx.html
  - https://www.bestbuy.com/site/asus-geforce-rtx-3080-10gb-gddr6x-pci-express-4-0-strix-graphics-card-black/6432445.p?skuId=6432445
  - https://www.bestbuy.com/site/evga-geforce-rtx-3080-ftw3-gaming-10gb-gddr6x-pci-express-4-0-graphics-card/6436191.p?skuId=6436191
  - https://www.bestbuy.com/site/evga-geforce-rtx-3080-ftw3-ultra-gaming-10gb-gddr6-pci-express-4-0-graphics-card/6436196.p?skuId=6436196
  - https://www.bestbuy.com/site/evga-geforce-rtx-3080-xc3-black-gaming-10gb-gddr6x-pci-express-4-0-graphics-card/6432399.p?skuId=6432399
  - https://www.bestbuy.com/site/evga-geforce-rtx-3080-xc3-gaming-10gb-gddr6-pci-express-4-0-graphics-card/6436194.p?skuId=6436194
  - https://www.bestbuy.com/site/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6-pci-express-4-0-graphics-card/6432400.p?skuId=6432400
  - https://www.bestbuy.com/site/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6-pci-express-4-0-graphics-card/6436195.p?skuId=6436195
  - https://www.bestbuy.com/site/gigabyte-geforce-rtx-3080-10g-gddr6x-pci-express-4-0-graphics-card-black/6430620.p?skuId=6430620
  - https://www.bestbuy.com/site/gigabyte-geforce-rtx-3080-10g-gddr6x-pci-express-4-0-graphics-card-black/6430621.p?skuId=6430621
  - https://www.bestbuy.com/site/gigabyte-geforce-rtx-3080-10g-gddr6x-pci-express-4-0-graphics-card-black/6436223.p?skuId=6436223
  - https://www.bestbuy.com/site/gigabyte-geforce-rtx-3080-10g-gddr6x-pci-express-4-0-graphics-card-white/6436219.p?skuId=6436219
  - https://www.bestbuy.com/site/msi-geforce-rtx-3080-ventus-3x-10g-oc-bv-gddr6x-pci-express-4-0-graphic-card-black-silver/6430175.p?skuId=6430175
  - https://www.bestbuy.com/site/nvidia-geforce-rtx-3080-10gb-gddr6x-pci-express-4-0-graphics-card-titanium-and-black/6429440.p?skuId=6429440
  - https://www.bestbuy.com/site/pny-geforce-rtx-3080-10gb-xlr8-gaming-epic-x-rgb-triple-fan-graphics-card/6432655.p?skuId=6432655
  - https://www.bestbuy.com/site/pny-geforce-rtx-3080-10gb-xlr8-gaming-epic-x-rgb-triple-fan-graphics-card/6432658.p?skuId=6432658
  - https://www.gamestop.com/video-games/pc/components/graphics-cards/products/tuf-gaming-geforce-rtx-3080-graphics-card/11109446.html
  - https://www.samsclub.com/p/pny-geforce-rtx3080-10gb-graphics-card/prod25090929
  - https://www.samsclub.com/p/pny-geforce-3080-10gb-xlr8-gaming-card/prod25090930
  - https://www.amazon.com/dp/B08HBR7QBM?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HBTJMLJ?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HH5WF97?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HHDP9DW?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HJS2JLJ?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HJTH61J?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HR3DPGW?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HR3Y5GQ?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HR4RJ3Q?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HR55YB5?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HR5SXPS?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HR6FMF3?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HR7SV3M?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08HVV2P4Z?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08J6F174Z?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08KGZVKXM?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08KJ3VKLQ?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/dp/B08QW8BKDV?tag=nismain-20&amp;linkCode=ogi&amp;th=1&amp;psc=1
  - https://www.amazon.com/gp/offer-listing/B08HJNKT3P?SubscriptionId=AKIAJF4X3QDDEUEKC7FA&amp;tag=nismain-20&amp;linkCode=xm2&amp;camp=2025&amp;creative=5143&amp;creativeASIN=B08HJNKT3P&amp;m=ATVPDKIKX0DER
...
